I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/multiverse-generator-screen.rpy", line 16, in script
    $ renpy.pause()
  File "game/code/multiverse-generator-screen.rpy", line 16, in <module>
    $ renpy.pause()
  File "game/code/multiverse-generator-screen.rpy", line 43, in execute
    screen multiverse_generator():
  File "game/code/multiverse-generator-screen.rpy", line 43, in execute
    screen multiverse_generator():
  File "game/code/multiverse-generator-screen.rpy", line 72, in execute
    hbox:
  File "game/code/multiverse-generator-screen.rpy", line 76, in execute
    for i in range (top_artificial_dimensions_number) < top_artificial_dimensions_number:
  File "game/code/multiverse-generator-screen.rpy", line 76, in <module>
    for i in range (top_artificial_dimensions_number) < top_artificial_dimensions_number:
TypeError: an integer is required

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/multiverse-generator-screen.rpy", line 16, in script
    $ renpy.pause()
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/code/multiverse-generator-screen.rpy", line 16, in <module>
    $ renpy.pause()
  File "renpy/exports.py", line 1563, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3737, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/screen.py", line 436, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3737, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/screen.py", line 447, in per_interact
    self.update()
  File "renpy/display/screen.py", line 637, in update
    self.screen.function(**self.scope)
  File "game/code/multiverse-generator-screen.rpy", line 43, in execute
    screen multiverse_generator():
  File "game/code/multiverse-generator-screen.rpy", line 43, in execute
    screen multiverse_generator():
  File "game/code/multiverse-generator-screen.rpy", line 72, in execute
    hbox:
  File "game/code/multiverse-generator-screen.rpy", line 76, in execute
    for i in range (top_artificial_dimensions_number) < top_artificial_dimensions_number:
  File "game/code/multiverse-generator-screen.rpy", line 76, in <module>
    for i in range (top_artificial_dimensions_number) < top_artificial_dimensions_number:
  File "renpy/python.py", line 1052, in revertable_range
    return RevertableList(range(*args))
TypeError: an integer is required

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Fucksekai 1.0
Mon Apr  4 10:43:42 2022
